volumes:
  pg_project_old:


services:
  pg_db:
    image: postgres:latest
    restart: always
    container_name: old_tg_bot_template_postgres
    hostname: ${POSTGRES_HOST}
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_project_old:/var/lib/postgresql/tg_bot_template
    ports:
      - "5433:5432"

  redis_fsm:
    image: redis:latest
    hostname: ${FSM_REDIS_HOST:-localhost}
    command: redis-server --requirepass "${FSM_REDIS_PASS:-}"
    env_file:
      - .env
    ports:
      - "6380:6379"

  tg_bot:
    container_name: old_tg_bot_template
    build: .
    env_file:
      - .env
    restart: always
    depends_on:
      - pg_db
      - redis_fsm
